import { chatJSON } from "@/lib/llm";
import type { ReelScene } from "@/lib/reel-types";

/**
 * Writes a shootable storyboard for one video post.
 *
 * Exists because the creative stage's `videoPrompt` covers only some video
 * posts and, where it does, gives a prose scene description with no separation
 * between what the camera sees, what is said, and what is written on screen.
 * Those three drive different jobs — the still frame, the voiceover, the
 * caption overlay — so they are captured as separate fields here. Keeping
 * on-screen text out of `shot` is what stops the frame generator from trying
 * to render lettering, which it cannot do legibly.
 */

export type GeneratedStoryboard = {
  totalDuration: string;
  overallDirection: string;
  hook: string;
  cast: string;
  scenes: ReelScene[];
};

export async function generateStoryboard(input: {
  brandName: string;
  industry?: string;
  topic: string;
  platform: string;
  contentType: string;
  conceptName?: string;
  insight?: string;
  emotionalTone?: string;
  aesthetic?: string;
  whyThisPost?: string;
  /** Free-text direction from the user, if they asked for something specific. */
  instruction?: string;
}): Promise<GeneratedStoryboard> {
  const result = await chatJSON<GeneratedStoryboard>(
    [
      {
        role: "system",
        content: [
          "You are a director of short-form social video, storyboarding one post.",
          "",
          "Before answering, think through: what makes someone stop scrolling in the first",
          "second -> what the middle has to earn -> what the last frame should leave behind.",
          "Do not include that reasoning in your answer.",
          "",
          "Write 4-7 scenes. Every scene needs four things, kept strictly separate:",
          '  - "timing": a range like "0:00-0:04". Scenes must run consecutively from 0:00',
          "    and add up to the total duration.",
          '  - "shot": ONLY what the camera sees — subject, framing, camera move, location,',
          "    light. This is also fed to an image model to render the frame, so it must",
          "    describe ONE moment and must contain NO text, lettering, signage, captions,",
          "    numbers or logos, no aspect ratios, and no hex codes. Name colours in words.",
          '  - "voiceover": what is said over the scene, as the actual words to be spoken.',
          "    Null if the scene is silent.",
          '  - "onScreenText": the words burned onto the frame, under 10 words. Null if none.',
          "    This is deliberately NOT part of the shot — it is added in the edit, because",
          "    an image model renders lettering as gibberish.",
          "",
          "Craft: open on motion or a face, never on a logo. Cut on action or breath.",
          "Prefer one concrete specific over three generic claims. Write voiceover the way",
          "people actually speak, contractions and all — not marketing copy read aloud.",
          "",
          "This may be any industry — never assume one. Ground every scene in the specific",
          "topic below, not in generic social-video boilerplate.",
          "",
          'CASTING. Each frame is generated by a separate image call with no memory of the',
          "others, so an unnamed person becomes a different person every scene. Write a",
          '"cast" line: one locked, concrete description of the person who recurs — apparent',
          "age, build, skin tone, hair length/colour/how it is worn, one memorable facial",
          "detail, and the exact clothing they wear throughout. It gets repeated verbatim",
          "into every scene, so it must stay true for the whole reel: no costume changes, no",
          '"later she wears". Describe a real, ordinary-looking person, not a model. If no',
          'person recurs, set "cast" to an empty string.',
          "Then, in each shot, refer to them as 'the woman'/'the man'/'the rider' — never",
          "re-describe their appearance, or the two descriptions will fight each other.",
          "",
          'Reply as JSON: { "totalDuration": "e.g. 38 seconds", "overallDirection": "one',
          'paragraph on look, pace, sound and edit style", "hook": "the opening line, under',
          '15 words", "cast": "the locked character description, or empty string",',
          '"scenes": [ { "timing", "shot", "voiceover", "onScreenText" } ] }',
        ].join("\n"),
      },
      {
        role: "user",
        content: [
          `Brand: ${input.brandName}`,
          input.industry ? `Category: ${input.industry}` : "",
          `Platform: ${input.platform}`,
          `Format: ${input.contentType}`,
          `Topic: ${input.topic}`,
          input.conceptName ? `Creative concept: ${input.conceptName}` : "",
          input.insight ? `Insight: ${input.insight}` : "",
          input.emotionalTone ? `Emotional tone: ${input.emotionalTone}` : "",
          input.aesthetic ? `Visual style: ${input.aesthetic}` : "",
          input.whyThisPost ? `Why this post exists: ${input.whyThisPost}` : "",
          input.instruction ? `\nSpecific direction from the user: ${input.instruction}` : "",
          "",
          "Storyboard this video.",
        ]
          .filter(Boolean)
          .join("\n"),
      },
    ],
    { creative: true, maxTokens: 3000, temperature: 0.7, jsonRetries: 2 },
  );

  const scenes = (result?.scenes ?? []).filter((s) => s && s.shot?.trim());
  if (scenes.length === 0) {
    throw new Error("The reel director returned no usable scenes.");
  }

  return {
    totalDuration: result.totalDuration?.trim() || `${scenes.length * 6} seconds`,
    overallDirection: result.overallDirection?.trim() || "",
    hook: result.hook?.trim() || "",
    cast: result.cast?.trim() || "",
    scenes: scenes.map((s) => ({
      timing: s.timing?.trim() || "",
      shot: s.shot.trim(),
      voiceover: s.voiceover?.trim() || null,
      onScreenText: s.onScreenText?.trim() || null,
    })),
  };
}
